apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uhdtk3jof-python 
  janus-idp.io/tekton: uhdtk3jof-python
  backstage.io/kubernetes-id: uhdtk3jof-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uhdtk3jof-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml